### ISSUE TITLE
Advanced Custom Fields

### ISSUE THREAD

**Issue by ghost** [stuttter/wp-chosen#8]
I just wanted to let you know there is something fishy with the ACF (5.5.13) and WP Chosen (3.0.0)

_Without WP Chosen:_

![acf-without-wp-chosen](https://cloud.githubusercontent.com/assets/19433935/25901919/d25e22a2-35a0-11e7-98dd-bb5613698595.png)
_With WP Chosen_

![acf-with-wp-chosen](https://cloud.githubusercontent.com/assets/19433935/25901921/d29088e6-35a0-11e7-8c3d-c1a124bdee85.png)

No console errors. It was fine with 2.1.0 😃 

Not a big deal if these kinds of conflicts are not in the scope of the projects 👍

**Comment by ryanjbonnell** [comment]
I can confirm this issue exists, but only when _editing_ an ACF Pro field, not when creating a new one.

The behavior is affecting the **Field Type** dropdown:

![screen shot 2017-06-02 at 12 04 15 pm](https://cloud.githubusercontent.com/assets/133372/26740756/b789df00-478b-11e7-8c1f-2193b2026414.png)

This issue seems to affect both [ACF 4.x][1] and [ACF Pro 5.x][2].

Tested using WP Chosen 3.0.0 and WordPress 4.7.5.

[1]: https://wordpress.org/plugins/advanced-custom-fields/
[2]: https://www.advancedcustomfields.com/pro/

**Comment by alpipego** [comment]
Possibly the same bug as in #9 (and potential fix in #10). ACF probably also hides and shows fields on click - therefore acting on the click event as such results in the chosen select to have a width of 0px.

**Comment by JJJ** [comment]
For ACF and other selects that are dynamically added, I think we'll need a `MutationObserver` implementation to watch for new `select` elements and dynamically `chosen()` them.

**Comment by alpipego** [comment]
I figured because of

> but only when editing an ACF Pro field, not when creating a new one.

it's related to the issue in #9. 
From a UX side, `select` elements not having chosen applied, are better than chosen divs with a width of 0px.

**Comment by JJJ** [comment]
The `wpChosenDelayedRefresh` javascript function will help refresh Chosen fields when other actions occur. WordPress Core meta-boxes do trigger a `postbox-toggled` action. If anyone who is using ACF wants to help out, there's where you'd want to start looking. 🙏

**Comment by JJJ** [comment]
Fixing in 6.0.0
